apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "dask.fullname" . }}-master
  labels:
    app: {{ template "dask.name" . }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "dask.chart" . }}
    component: master
spec:
  template:
    spec:
      containers:
        - name: {{ template "dask.fullname" . }}-master
          image: "{{ .Values.master.image.repository }}:{{ .Values.master.image.tag }}"
          imagePullPolicy: {{ .Values.master.image.pullPolicy }}
          {{- if .Values.master.args }}
          args:
            {{- toYaml .Values.master.args | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.master.resources | nindent 12 }}
          volumeMounts:
            - name: shared-data
              mountPath: /data
          env:
            - name: DASK_SCHEDULER_ADDRESS
              value: {{ template "dask.fullname" . }}-scheduler:{{ .Values.scheduler.servicePort }}
          {{- if .Values.master.env }}
            {{- toYaml .Values.master.env | nindent 12 }}
          {{- end }}
      nodeSelector:
        {{- toYaml .Values.master.nodeSelector | nindent 8 }}
      volumes:
      - name: shared-data
        persistentVolumeClaim:
          claimName: {{ template "dask.fullname" . }}-shared-data
    {{- with .Values.master.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.master.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      restartPolicy: OnFailure
  backoffLimit: 4

